### ISSUE TITLE
Ensure all repos have websites built by travis

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidy-dev-day#13]
- [x] glue (@jimhester)
- [x] stringr (@hadley)
- [x] tidyverse (@hadley)
- [x] haven (@hadley)
- [x] forcats (@hadley)
- [x] blob (@hadley)
- [x] lubridate (@hadley)
- [x] magrittr (@hadley)
- [x] dplyr (@hadley)
- [ ] tibble (@krlmlr)
- [ ] hms (@krlmlr)
- [ ] googlesheets4 (@jennybc)
- [ ] googledrive (@jennybc)

**Comment by jimhester** [comment]
I did glue's website yesterday

**Comment by batpigandme** [comment]
glue gets a happy little ☑️ then, @jimhester!

**Comment by hadley** [comment]
I'm iteratively improving the instructions at https://github.com/r-lib/usethis/issues/535

**Comment by jennybc** [comment]
Do we really mean to have this here? Not sure it's the sort of thing a non-maintainer can make a lot of progress on via PR.

**Comment by jennybc** [comment]
Or is this something you want us to do *in preparation for tidyverse dev day* @hadley? 🤔

**Comment by batpigandme** [comment]
It's in prep for TDD.
