### ISSUE TITLE
Photos from 2019 January dev day after rstudio::conf

### ISSUE THREAD

**Issue by jennybc** [tidyverse/tidy-dev-day#18]
Can we link to some of the photos taken at this event? We should capture some of that.

**Comment by raynamharris** [comment]
This album from @CerebralMastication has lots of photos from developer day. 

https://twitter.com/CMastication/status/1086763450993389569

https://photos.google.com/share/AF1QipMZwkL0M_MSQUPOB-HX2eppEvcmDMwF4CI_Wa81BrtnjpZBKKkXCtZ2TOzvX80ctQ?key=ekN5Zk9wMFAySlc5cTJuOW1vekFXRTh1LXJJOVBR

**Comment by hadley** [comment]
It feels a bit weird to me to for us to "officially" share these photos without getting permission of the people pictured.
