### ISSUE TITLE
Notes for next time

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidy-dev-day#22]
* need package stickers for issues wall (maybe make some bigger wall stickers like I have in my office?)
* yellow = docs, red = bug, green = issue worked well
* documentation issues ran out pretty quickly
* should ask people to write their PR number on the post it
* need to reinforce PR title + description structure
* stickers need to go at __top__ of post-it
* have submitters ring the gong, not the merger
* since process was more efficient, need even more documentation/smaller issues
* a few table tents to seed collaboration around a package

**Comment by jennybc** [comment]
* participant rings gong when their PR gets merged (vs. us doing it)

Maybe they pick up a "welcome" handout, with key steps of the workflow laid out + space to stick their first issue & post-it.

**Comment by jennybc** [comment]
Have people do one simple PR before they show up, similar to adding an adjective to the praise package. This will help people get setup done in advance.

**Comment by hadley** [comment]
Or request food (by specifying dietary preferences)

**Comment by jennybc** [comment]
@romain raised the idea of using gitter.

Could be a good way to open up some discussion in the days just before, during, and after. Could also a short-lived slack channel.

**Comment by hadley** [comment]
Size (30 URM, 30 general entry, 20 helpers) felt good.

**Comment by jyuu** [comment]
Live stream a few distributed pair programming exercises during dev days? Maybe a way to learn and practice how to debug and/or how pair programming works?

**Comment by hadley** [comment]
A few more notes/ideas from survey feedback:

* Need to do some sort of mixer/icebreaker just to get more people talking to each other.
* Encourage people to tackle solo documentation issue in the morning, and then pair up to tackle bug/feature after lunch?
* More info about what happens if you don't get your PR reviewed on the day.
* More modelling of PR process - maybe do a video beforehand?
