### ISSUE TITLE
Find a barista

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidy-dev-day#34]
Need to locate a barista/coffee cart that can serve good espresso coffee (plus other drinks) to ~100 folks from 9am to 3pm.

Just to spit ball the barrista cost: I think we’d want 6 hours (0900-1500) of service for ~100 people, which with https://www.espressoelegance.com/espresso-catering-rates would be $1875

**Comment by DavisVaughan** [comment]
Likely https://www.espressoelegance.com/#espresso-catering-seattle just because they have a custom latte art printer 😆  https://www.instagram.com/p/CanBpGnJz8M/?igsh=NGE5ODI0NTFsdXFx

Possibly https://www.brewinaround.com/ but way less reviews

**Comment by hadley** [comment]
Signed contract with espresso elegance.
