### ISSUE TITLE
Elect the adhesive czar

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidy-dev-day#35]
- [ ] Converts issues labelled with TDD to labels
- [ ] Print out labels
- [x] Bring the post its
- [x] Find small stickers for labelling related issues
- [x] Bring the name label stickers
- [x] Sharpies
- [x] Something to indicate "no photography"

**Comment by hfrick** [comment]
* no-photography-signal?

**Comment by hfrick** [comment]
I've just placed an order for various adhesive things + sharpies ✨
