### ISSUE TITLE
First time PR worksheet

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidy-dev-day#47]
Create a welcome doc that outlines the basic steps to contribute, including a space to stick the post it.

The goal is to create a worksheet that someone who has never done a PR before can work through step-by-step to successful create a documentation PR. It should match our general advice in the readme, but can provide more detail and should provide various places to write in information.

**Comment by jennybc** [comment]
The README of this repo has a good start, but needs work.

The advice to do `pak::pak()` catches my eye, because I know I have had to help lots of people do `pak::local_install_dev_deps()` instead of just `pak::pak()`. We should make sure to include this advice.

**Comment by jennybc** [comment]
Maybe knockoff https://github.com/r-lib/usethis/issues/1491 at the same time
