### ISSUE TITLE
Pre-work email + office hours

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidy-dev-day#49]
* Create a repo with some fun file (like praise, or use praise)
* Every participant should do a PR (if they haven't before)
* Office hour for folks who get stuck

**Comment by jennybc** [comment]
I just replied to an inquiry with this text, which seems like a very crude start at some pre-work advice:

> I think we will reach out to folks with advice on preparation. But the short version is that you'd want to get your basic Git/GitHub setup sorted out in advance and try to make a small pull request somewhere. Like on the level of adding an adjective to the praise package, in terms of scope. Just prove that the basic mechanics work. Some people show up without even doing this, but that makes it very likely you won't get much done *other* than completing this sort of setup, which seems like sort of a waste.
> 
> * Good source for getting the basic set up done: https://happygitwithr.com/
> * Example of small PR: https://usethis.r-lib.org/articles/pr-functions.html (this uses usethis functions to make the PR, which we like, but mostly I just want to indicate what a small PR looks like)
> * Preparing a system for package dev: https://r-pkgs.org/setup.html
