### ISSUE TITLE
Fred Hutch logistics

### ISSUE THREAD

**Issue by jennybc** [tidyverse/tidy-dev-day#58]
Jotting down specific info that is otherwise just floating around in my email.

* Sana Hirata (Program Administrator /  Fred Hutch Data Science Lab (FH DaSL)) is our main contact. Jenny has their contact info.
* Reserved spaces:
  - Tidyverse:
    * S1-141/142 (H) O'Mack Symposium Suite) 8:00-5:00pm. Will be set up "classroom style", which was settled after showing photos of a previous dev day and how people work.
    * "The room [O'Mack Symposium Suite] has the following features that can be utilized: PC computer, projector, ceiling speakers, conference camera, counter space in the back of the room, lectern, built-in wireless mic, projection screen, and white boards."
    * S1-104: Work Lounge  8:00-5:00pm
    * "The Work Lounge would work great for coffee and food or having small group meeting sessions. There is also a long counter in the O’Mack Suites that could be suitable for coffee, or food/lunch."
    * "This room [Work Lounge] is located just across the hall from the O’Mack Suites. There are restrooms located between the two locations."
    * We have explicitly discussed the need for folks to power their laptops and the IT folks have confirmed this is recorded as part of our reservation. 
    * "S" stands for Steam Plant Building
    * The address for the Steam Plant is 1201 Eastlake Ave. E. Seattle 98102.
  - R Core Dev Event:
    * D1-084 (Classroom format, 25 people) 8:00am-2:30pm
    * "D" stands for Thomas Building, about 10 minute walk from Steam Plant
  - R Core Dev (Remote Participant Collaboration)
    * D1-302 8:00-11:00am
    * D1-302 12:30-3:00pm
    * S3-153 1:00-5:00pm
* "Folks can connect to Guest wifi – they will just need to accept the terms."

**Comment by jennybc** [comment]
[Fred Hutch Campus Map.pdf](https://github.com/user-attachments/files/16416775/Fred.Hutch.Campus.Map.pdf)

**Comment by jennybc** [comment]
![Tidyverse Dev Day Back](https://github.com/user-attachments/assets/82b75fb6-bc6b-41fc-b520-79cf5eff32b5)
![Tidyverse Dev Day Front](https://github.com/user-attachments/assets/cad6ded6-cf90-42e3-8aab-9ec63d0c4cf2)
![Tidyverse Dev Day North](https://github.com/user-attachments/assets/95d8fc3e-3c3c-4a2d-99d7-1ff61c14a888)
![Tidyverse Dev Day South](https://github.com/user-attachments/assets/26b4ab12-e3f3-4978-bcfe-ac87b2e107a1)

**Comment by DavisVaughan** [comment]
Barista logistics

> The espresso cart is delivered in one of our three specialized delivery trucks, complete with a lift-gate that can accommodate loading docks as well as street loading zones. Our delivery team is committed to efficient delivery of our equipment with an estimated unload time of 15 minutes or less, causing little to no downtime for you and your staff.

> Everything is self-contained within our espresso carts. All we need from you is access to a standard 110 electrical outlet on a dedicated circuit. Once the cart is setup, we need a 7 foot by 4 and a half foot space in order to operate. The espresso cart is 4 feet in length prior to being setup and can easily fit in an elevator!

We have them starting at 9am, but they will want to set up earlier, so it is good that we can get in the room at 8am

**Comment by jennybc** [comment]
TRANSPORTATION & PARKING OPTIONS

Fred Hutch is dedicated to the promotion of alternate modes of commuting. Our goal is to have less single occupancy vehicles on the Fred Hutch campus and on the road. Fred Hutch maintains an ongoing commitment to the City of Seattle’s approved Transportation Management Plan (TMP) and Washington State’s Commute Trip Reduction Program (CTR).

Commuting Alternatives:

**Bus Route**:

For details, visit the [Metro Transit website](https://kingcounty.gov/en/dept/metro).

* Find the right bus route for you: Use [Google Maps](https://maps.google.com/) to customize your route based on your input.
* Real-time transit information: Check [One Bus Away](https://onebusaway.org/) for real-time updates for King County.

Route

Closest Stops

Frequency

Route

[70](http://kingcounty.gov/depts/transportation/metro/schedules-maps/070.aspx#weekday)

Fairview Ave. N. and Aloha St. 

~15 minutes 

Runs on Eastlake and Fairview Ave from University District to downtown

[Rapid Ride C line](http://kingcounty.gov/depts/transportation/metro/schedules-maps/c-line.aspx)

Fairview Ave. N. and Valley St.

~7-10 minutes

Runs on Fairview Ave from West Seattle through downtown Seattle to South Lake Union

**Seattle Street Car**

The South Lake Union line of the Seattle Streetcar conveniently connects to other public transit systems, including Metro buses, Sound Transit buses, Link light rail, and the Monorail. Visit the [Seattle Streetcar page](https://seattlestreetcar.org/) for more details.

**Campus Parking**

Parking on campus is very limited. There are limited paid lots on a first come-first serve basis.

* Aloha lot: East of the Minor building, accessed from Aloha St. or Minor Ave. There are parking kiosk in the parking lot.
* Yale lot: In front of the Yale building, accessed from Yale Ave. N.
* Fairview lot: East of the Fairview building, accessed from Yale Ave. N.
 
**Garage in South Lake Union**

Due to limited parking on campus, using [SpotHero](https://spothero.com/) guarantees a parking spot booked in advance in a nearby garage. Options within a 10-15 min walk include:

1121 Republican St
219 Galer St
1263 Republican St

**Comment by shannonpileggi** [comment]
Just looked up transportation directly from the Hyatt Regency hotel. It looks like it is about a 1 mile walk to the campus from the hotel, or people can pick up the 70 bus a five minute walk from the hotel at Virginia St & 9th Ave. 

A single one way fare on the bus is $2.75. 
* The easiest way to pay for your ride is with an ORCA card, which you can purchase at a ticket machine. 
* Ticket machines accept cash and credit/debit cards such as Visa or MasterCard. 
* Or buy a ticket on your phone with the Transit GO Ticket app.
* Buses also accept exact cash fares.
